Feature/sailing fleet
Kalaxia/client pull request #10
Opened 2020-05-25 17:46 UTC by ChickenStorm

2020-05-27 10:29 UTC, Kern046 requested changes
Première review rapide

2020-05-27 10:29 UTC, Kern046 commented on global/store.gd
> +	for system in _state.game.systems:
fleet contient le system_id auquel il appartient. Tu n'as pas besoin de boucler sur chaque système pour le retrouver :) !

2020-05-27 10:29 UTC, Kern046 commented on game/map/system.gd
> +			Store.system_select_destination_fleet(system)
En fait ici tu appelles le Store pour faire parvenir un événement à game.gd qui lui s'occupe de faire la requête HTTP.

Je trouve que ça ajoute des couches et de la complexité pour quelque chose qui peut rester très simple : tu peux faire la requête HTTP de déplacement directement ici. Dans la condition je rajouterais également Store._state.selected_fleet != null, pour ne trigger ce code que si une flotte a été sélectionnée au préalable.

2020-05-27 10:29 UTC, Kern046 commented on global/store.gd
> +func system_select_destination_fleet(system):
A supprimer du coup suite à mon commentaire sur system.gd

2020-05-27 10:29 UTC, Kern046 commented on game/game.gd
> +	Store.connect("system_select_destination_fleet",self,"_on_system_select_destination_fleet")
A supprimer du coup suite à mon commentaire sur system.gd

2020-05-27 10:29 UTC, Kern046 commented on game/game.gd
> +func _on_system_select_destination_fleet(system):
A supprimer du coup suite à mon commentaire sur system.gd.

Pour le selected_fleet à remettre à null dans le store, tu peux le déplacer à l'endroit où la requête HTTP de déplacement est confirmée, dans system.gd

2020-05-27 10:29 UTC, Kern046 commented on game/game.gd
> +var is_fleet_selected = false
A supprimer du coup suite à mon commentaire sur system.gd

2020-05-27 16:54 UTC, ChickenStorm commented on global/store.gd
> +	for system in _state.game.systems:
Justement sauf dans le cas où elle a été bougée. le system_id le nouveau system

2020-05-27 20:06 UTC, Kern046 commented on game/map/system.gd
> +			if Store._state.selected_fleet != null && Store._state.selected_fleet.system.id != system.id:
Tu peux fusionner les deux conditions ensemble :)

2020-05-27 20:11 UTC, Kern046 commented on global/store.gd
> +	for system in _state.game.systems:
je pense que dans ce cas il faudrait adapter la fonction en sorte de move_fleet(fleet, old_system) où fleet contiendrait le nouveau système et la fonction prendrait en paramètre l'ancien

2020-05-27 20:12 UTC, Kern046 commented on global/store.gd
> +func get_fleet_id(fleet_id):
où as-tu besoin de cette fonction ?

2020-05-28 05:13 UTC, ChickenStorm commented on global/store.gd
> +func get_fleet_id(fleet_id):
en effet je ne l'utilise pas tu veux que je l'enlève?

2020-05-28 17:11 UTC, ChickenStorm commented on matchmaking/player/player_info.gd
> +	if player.faction != null:
correction d'un bug mineur

2020-05-28 17:12 UTC, ChickenStorm commented on matchmaking/player/player_info.gd
> +		get_node("Container/FactionChoice").selected = player.faction
correction d'un bug mineur

2020-05-29 18:45 UTC, Kern046 approved these changes

2020-05-29 18:45 UTC, merged