Feature/galaxy map
Kalaxia/client pull request #21
Opened 2020-06-14 10:34 UTC by ChickenStorm

2020-06-14 12:32 UTC, Kern046 requested changes

2020-06-14 12:32 UTC, Kern046 commented on game/game.gd
> +		if _is_map_being_dragged:
ici, au lieu d'un if/else, faire une variable ``coeff`` avec un ternaire:

```gdscript
var coeff = CAMERA_DRAG_COEFF_WHEN_DRAGGING if _is_map_being_dragged else CAMERA_DRAG_COEFF
```

Ensuite tu n'as plus qu'à faire ``abs_vector.x = // ...`` et ``abs_vector.y = // ...`` une seule fois.

2020-06-14 12:32 UTC, Kern046 commented on game/game.gd
> +const CAMMERA_DRAG_COEF = 4000.0
CAMERA avec un seul M, COEFF avec deux F !

2020-06-14 12:32 UTC, Kern046 commented on menu/option_key_binding.gd
> +	if action_param != action:
Petit ternaire ici je pense

2020-06-14 12:32 UTC, Kern046 commented on menu/option_key_binding.gd
> +		if node is Button:
fusionner les if ?

2020-06-14 12:32 UTC, Kern046 commented on menu/option_key_binding.gd
> +	if index_pressed  != -1:
sur ce genre de fonction, j'aurais plutôt tendance à inverser la condition et faire un return, afin de désindenter le reste du code

2020-06-14 23:19 UTC, ablanleuil commented on menu/option_key_binding.gd
> +	if state:
Mieux vaut donner un nom explicite aux variables, surtout si c'est un booléen, ça permet de savoir à quelle question on répond. Ici `state` veut dire "est appuyé" j'imagine ?

2020-06-18 11:35 UTC, Kern046 requested changes
Rien à dire à part le lien Discord périmé et des typo, c'est top !

2020-06-18 11:35 UTC, Kern046 commented on menu/menu_credits.gd
> +	$CenterContainer/VBoxContainer/GridContainer/LinkButtonDiscord.connect("pressed",self,"_on_link_button_press",["https://discordapp.com/invite/hCqAcY"])
Lien périmé, remplacer par : https://discord.com/invite/mDTms5c

2020-06-18 11:35 UTC, Kern046 commented on menu/menu_credits.tscn
> +text = "Retour au menu principale"
"principal"

2020-06-18 11:35 UTC, Kern046 commented on menu/menu_option.tscn
> +text = "Retour au menu principale"
"principal"

2020-06-18 11:35 UTC, Kern046 commented on menu/menu_credits.tscn
> +text = "Développer par la communauté Kalaxia"
"Développé" "communauté de Kalaxia"

2020-06-18 11:35 UTC, Kern046 commented on menu/option_key_binding.gd
> +signal unmark_button_key_binging()
"binding"

2020-06-18 11:35 UTC, Kern046 commented on menu/option_key_binding.gd
> +var is_enable = false setget set_is_enabled
is_enabled

2020-06-18 11:35 UTC, Kern046 commented on menu/option_key_binding.gd
> +			node.disabled = ! is_enable
is_enabled

2020-06-18 11:35 UTC, Kern046 commented on menu/option_key_binding.gd
> +	is_enable = new_value
is_enabled

2020-06-18 11:35 UTC, Kern046 commented on menu/menu_option.gd
> +				node_key.is_enable = true
is_enabled

2020-06-20 16:39 UTC, Kern046 approved these changes

2020-06-20 16:40 UTC, merged